name: Repository Dispatch Action

on:
  repository_dispatch:
    types: 
      - event1
      - event2

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 Hello World!"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in Repository
        run: |
          echo "This example for Repository Dispatch trigger will list the files in the repository ${{ github.repository }}:" 
          tree
          ls -lah
      - run: |
          echo "Payload: ${{ toJSON(github.event.client_payload) }}"
        name: Payload 
        if: ${{ github.event.event_name == 'repository_dispatch' }}


# gh api -X POST -H "Accept: application/vnd.github.v3+json"/repos/kasunsjc/GitHubActionInAction/dispatches -f event_type=event1 -f 'client_payload[passed]=false' -f 'client_payload[message]=Error: timeout'

# curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/kasunsjc/GitHubActionInAction/dispatches -d '{"event_type":"event1"}'